version: "3.9"

configs:
  rabbitmq_conf:
    file: ./infra/rabbitmq/rabbitmq.conf
  rabbitmq_enabled_plugins:
    file: ./infra/rabbitmq/enabled_plugins
  rabbitmq_definitions:
    file: ./infra/rabbitmq/definitions.json
  ca_cacert:
    file: ./infra/tls/certificates/testca/cacert.pem
  ca_cert:
    file: ./infra/tls/certificates/server/cert.pem
  ca_key:
    file: ./infra/tls/certificates/server/key.pem

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    configs:
      - source: rabbitmq_conf
        target: /etc/rabbitmq/rabbitmq.conf
        uid: "100"
        gid: "101"
      - source: rabbitmq_enabled_plugins
        target: /etc/rabbitmq/enabled_plugins
        uid: "100"
        gid: "101"
      - source: rabbitmq_definitions
        target: /etc/rabbitmq/definitions.json
        uid: "100"
        gid: "101"
      - source: ca_cacert
        target: /etc/rabbitmq/tls/cacert.pem
        uid: "100"
        gid: "101"
      - source: ca_cert
        target: /etc/rabbitmq/tls/cert.pem
        uid: "100"
        gid: "101"
      - source: ca_key
        target: /etc/rabbitmq/tls/key.pem
        uid: "100"
        gid: "101"
    ports:
      # Plain TCP
      - "5672:5672/tcp"
      # SSL
      - "5671:5671/tcp"
      # Management console
      - "15672:15672/tcp"
    depends_on:
      ca:
        condition: service_completed_successfully
    extra_hosts:
      - "rabbitmq.example.org:127.0.0.1"
    restart: always

  ca:
    build:
      context: infra/tls
    volumes:
      - ./:/src

  "74": &php-base
    build: &php-base-build
      context: infra/php
      target: dev
      additional_contexts:
        php-core: docker-image://php:7.4-zts-bullseye
    volumes:
      - ./:/src
    depends_on:
      - rabbitmq
    ulimits:
      core: -1
    working_dir: /src/build/74
    links:
      - "rabbitmq:rabbitmq.example.org"

  "80":
    <<: *php-base
    build:
      <<: *php-base-build
      additional_contexts:
        php-core: docker-image://php:8.0-fpm-bullseye
    working_dir: /src/build/80

  "81":
    <<: *php-base
    build:
      <<: *php-base-build
      additional_contexts:
        php-core: docker-image://php:8.1-fpm-bookworm
    working_dir: /src/build/81

  "82":
    <<: *php-base
    build:
      <<: *php-base-build
      target: dev-all
      additional_contexts:
        php-core: docker-image://php:8.2-fpm-bookworm
    working_dir: /src/build/82
