version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - type: bind
        source: ./infra/rabbitmq/rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
        read_only: true
      - type: bind
        source: ./infra/rabbitmq/enabled_plugins
        target: /etc/rabbitmq/enabled_plugins
        read_only: true
      - type: bind
        source: ./infra/rabbitmq/definitions.json
        target: /etc/rabbitmq/definitions.json
        read_only: true
      - type: bind
        source: ./infra/tls/certificates
        target: /etc/rabbitmq/certificates
        read_only: true
    ports:
      # Plain TCP
      - "5672:5672/tcp"
      # SSL
      - "5671:5671/tcp"
      # Management console
      - "15672:15672/tcp"
    depends_on:
      ca:
        condition: service_completed_successfully
    extra_hosts:
      - "${PHP_AMQP_SSL_HOST}:127.0.0.1"
    restart: always

  ca:
    build:
      context: infra/tls
    volumes:
      - ./:/src

  centos-74: &centos-dev
    build: &centos-dev-build
      context: infra/dev
      target: redhatish
      args:
        php_version: "7.4"
      additional_contexts:
        base: docker-image://quay.io/centos/centos:stream9
    volumes:
      - ./:/src
    depends_on:
      - rabbitmq
    ulimits:
      core: -1
    working_dir: /src/build/centos-74
    env_file: .env
    links:
      - "rabbitmq:${PHP_AMQP_SSL_HOST}"

  centos-80:
    <<: *centos-dev
    build:
      <<: *centos-dev-build
      args:
        php_version: "8.0"
    working_dir: /src/build/centos-80

  centos-81:
    <<: *centos-dev
    build:
      <<: *centos-dev-build
      args:
        php_version: "8.1"
    working_dir: /src/build/centos-81

  centos-82:
    <<: *centos-dev
    build:
      <<: *centos-dev-build
      args:
        php_version: "8.2"
    working_dir: /src/build/centos-82

  centos-83:
    <<: *centos-dev
    build:
      <<: *centos-dev-build
      args:
        php_version: "8.3"
    working_dir: /src/build/centos-83

  ubuntu-74: &ubuntu-dev
    build: &ubuntu-dev-build
      context: infra/dev
      target: ubuntu-php
      args:
        php_version: "7.4"
      additional_contexts:
        base: docker-image://ubuntu:jammy
    volumes:
      - ./:/src
    depends_on:
      - rabbitmq
    ulimits:
      core: -1
    working_dir: /src/build/ubuntu-74
    env_file: .env
    links:
      - "rabbitmq:${PHP_AMQP_SSL_HOST}"

  ubuntu-80:
    <<: *ubuntu-dev
    build:
      <<: *ubuntu-dev-build
      args:
        php_version: "8.0"
    working_dir: /src/build/ubuntu-80

  ubuntu-81:
    <<: *ubuntu-dev
    build:
      <<: *ubuntu-dev-build
      args:
        php_version: "8.1"
    working_dir: /src/build/ubuntu-81

  ubuntu-82:
    <<: *ubuntu-dev
    build:
      <<: *ubuntu-dev-build
      args:
        php_version: "8.2"
    working_dir: /src/build/ubuntu-82

  debian-74: &debian-dev
    build: &debian-dev-build
      context: infra/dev
      target: debian
      additional_contexts:
        base: docker-image://php:7.4-zts-bullseye
    volumes:
      - ./:/src
    depends_on:
      - rabbitmq
    ulimits:
      core: -1
    working_dir: /src/build/debian-74
    env_file: .env
    links:
      - "rabbitmq:${PHP_AMQP_SSL_HOST}"

  debian-80:
    <<: *debian-dev
    build:
      <<: *debian-dev-build
      additional_contexts:
        base: docker-image://php:8.0-zts-bullseye
    working_dir: /src/build/debian-80

  debian-81:
    <<: *debian-dev
    build:
      <<: *debian-dev-build
      additional_contexts:
        base: docker-image://php:8.1-zts-bookworm
    working_dir: /src/build/debian-81

  debian-82:
    <<: *debian-dev
    build:
      <<: *debian-dev-build
      additional_contexts:
        base: docker-image://php:8.2-zts-bookworm
    working_dir: /src/build/debian-82

  debian-83:
    <<: *debian-dev
    build:
      <<: *debian-dev-build
      additional_contexts:
        base: docker-image://php:8.3-rc-zts-bookworm
    working_dir: /src/build/debian-83
