#define PHP_AMQP_VERSION_MAJOR 2
#define PHP_AMQP_VERSION_MINOR 0
#define PHP_AMQP_VERSION_PATCH 0
#define PHP_AMQP_VERSION_EXTRA "alpha2"
#define PHP_AMQP_VERSION "2.0.0alpha2"
#define PHP_AMQP_VERSION_ID 20000
