#!/usr/bin/env bash
PHP_VERSIONS=("8.3" "8.2" "8.1" "8.0" "7.4")
LIBRABBITMQ_VERSIONS=("master" "0.13.0" "0.12.0" "0.11.0" "0.10.0" "0.9.0" "0.8.0")

stringListToJson() {
  echo -n "["
  local pos=0
  for str in $@; do
    echo -n \"$str\"
    pos=$((pos + 1))
    [ $pos -lt $# ] && echo -n ", "
  done
  echo "]"
}

memoryMatrix() {
  pos=0
  max=$((${#PHP_VERSIONS[@]} * 2))
  echo -n "["
  for php_version in ${PHP_VERSIONS[@]}; do
    for librabbitmq_high_low in ${LIBRABBITMQ_VERSIONS[0]} ${LIBRABBITMQ_VERSIONS[${#LIBRABBITMQ_VERSIONS[@]} - 1]}; do
      pos=$((pos + 1))
      printf '{"php-version": "%s", "librabbitmq-version": "%s", "test-php-args": "-m", "compiler": "gcc"}' $php_version, $librabbitmq_high_low
      [ $pos -lt $max ] && echo -n ", "
    done
  done
  echo "]"
}

echo "php_versions=$(stringListToJson "${PHP_VERSIONS[@]}")"
echo "librabbitmq_versions=$(stringListToJson "${LIBRABBITMQ_VERSIONS[@]}")"
echo "memory_test_matrix=$(memoryMatrix)"