#!/usr/bin/env sh

set -o errexit
set -o nounset

extensions="json simplexml sodium"
args="-n \
  -d date.timezone=UTC \
  -d precision=20 \
  -d zend.enable_gc=On \
  -d display_errors=On \
  -d display_startup_errors=On \
  -d error_reporting=-1"

extension_dir=`php -r "echo ini_get('extension_dir');"`

for extension in $extensions; do
  code="echo extension_loaded('$extension') ? 'true' : 'false';"
  exists=$(php -r "$code")
  bundled=$(php -n -r "$code")
  if test "$exists" = "true" -a "${bundled}" = "false"; then
    args="${args} -d extension=$extension_dir/$extension.so"
  fi
done

$(which php) ${args} $@
