#!/usr/bin/env sh

set -o errexit
set -o nounset

base_dir=`dirname $0`/../../

if test ! -x $base_dir/vendor/bin/ecs; then
  composer --working-dir=$base_dir install
fi

$base_dir/vendor/bin/ecs --config=$base_dir/ecs.php $@