name: Test

on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]

env:
  TEST_TIMEOUT: 120
  CFLAGS: -g -O0 -fstack-protector-strong -Wall -Werror -D_GNU_SOURCE
  MAKEFLAGS: -j4 PHP_EXECUTABLE=./infra/tools/pamqp-php-cli-deterministic

jobs:
  prep:
    name: Prepare
    continue-on-error: true
    runs-on: ubuntu-22.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
      php_versions: ${{ steps.matrix.outputs.php_versions }}
      librabbitmq_versions: ${{ steps.matrix.outputs.librabbitmq_versions }}
      memory_build_matrix: ${{ steps.matrix.outputs.memory_build_matrix }}
    steps:
      - id: skip_check
        name: Prevent duplicate builds
        uses: fkirc/skip-duplicate-actions@v5.3.1
        with:
          skip_after_successful_duplicate: 'true'
          cancel_others: 'true'
          concurrent_skipping: 'same_content_newer'

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Prepare matrix
        id: matrix
        run: |
          infra/tools/pamqp-matrix >> "$GITHUB_OUTPUT"

  checkstyle:
    name: Check C formatting
    runs-on: ubuntu-22.04
    needs: prep
    if: needs.prep.outputs.should_skip != 'true'

    steps:
      - name: Install clang-format
        uses: myci-actions/add-deb-repo@11
        with:
          repo: 'deb https://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main'
          repo-name: llvm
          keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key
          install: clang-format-17

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Check style
        run: ./infra/tools/pamqp-format-check

  stubs:
    name: Check stubs php-${{ matrix.php-version }}
    runs-on: ubuntu-22.04
    needs: prep
    if: needs.prep.outputs.should_skip != 'true'

    strategy:
      fail-fast: false
      matrix:
        php-version: ${{ fromJson(needs.prep.outputs.php_versions) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install packages
        uses: awalsh128/cache-apt-pkgs-action@v1.4.3
        with:
          packages: cmake build-essential libssl-dev checkinstall zlib1g-dev

      - name: Load clang 11 cache
        id: clang-cache
        uses: actions/cache@v4
        with:
          path: /tmp/clang
          key: clang-11

      - name: Copy clang 11 cache after restore
        if: ${{ steps.clang-cache.outputs.cache-hit == 'true' }}
        run: sudo mv /tmp/clang /usr/local/clang

      - name: Manually install clang 11
        if: ${{ steps.clang-cache.outputs.cache-hit != 'true' }}
        run: |
          echo "Downloading clang 11.."
          wget -q https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.1/clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10.tar.xz
          echo "Extracting clang 11.."
          tar -xvf clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10.tar.xz > /dev/null
          sudo cp -r clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10 /usr/local/clang

      - name: Copy clang 11 cache before save
        if: ${{ steps.clang-cache.outputs.cache-hit != 'true' }}
        run: sudo cp -r /usr/local/clang /tmp/clang

      - name: Save clang 11 cache
        if: ${{ steps.clang-cache.outputs.cache-hit != 'true' }}
        id: clang-cache-save
        uses: actions/cache/save@v4
        with:
          path: /tmp/clang
          key: clang-11

      - name: Load cmake 3.22 cache
        id: cmake-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            /tmp/cmake
            /usr/local/bin/cmake
          key: cmake-3.22

      - name: Copy cmake 3.22 cache after restore
        if: ${{ steps.cmake-cache.outputs.cache-hit == 'true' }}
        run: sudo mv /tmp/cmake /usr/local/share/cmake-3.22

      - name: Manually install cmake 3.22
        if: ${{ steps.cmake-cache.outputs.cache-hit != 'true' }}
        run: |
          export OPENSSL_ROOT_DIR=/usr/include/openssl
          echo "Downloading cmake 3.22.."
          wget -q https://cmake.org/files/v3.22/cmake-3.22.6.tar.gz
          echo "Extracting cmake 3.22.."
          tar -xzvf cmake-3.22.6.tar.gz > /dev/null
          cd cmake-3.22.6
          ./bootstrap CC='/usr/local/clang/bin/clang' CFLAGS='-fPIE'
          make -j$(nproc) CC='/usr/local/clang/bin/clang' CFLAGS='-fPIE'
          sudo make install

      - name: Copy cmake 3.22 cache before save
        if: ${{ steps.cmake-cache.outputs.cache-hit != 'true' }}
        run: sudo cp -r /usr/local/share/cmake-3.22 /tmp/cmake

      - name: Save cmake 3.22 cache
        if: ${{ steps.cmake-cache.outputs.cache-hit != 'true' }}
        id: cmake-cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            /tmp/cmake
            /usr/local/bin/cmake
          key: cmake-3.22

      - name: Export cmake 3.22 path
        run: export PATH=/usr/local/bin/cmake:$PATH

      - name: Load openSSL 1.1 cache
        if: ${{ (matrix.librabbitmq-version == '0.10.0' || matrix.librabbitmq-version == '0.9.0' || matrix.librabbitmq-version == '0.8.0') }}
        id: openssl-cache
        uses: actions/cache/restore@v4
        with:
          path: /tmp/ssl
          key: openssl-1.1.1

      - name: Copy openSSL 1.1 cache after restore
        if: ${{ (matrix.librabbitmq-version == '0.10.0' || matrix.librabbitmq-version == '0.9.0' || matrix.librabbitmq-version == '0.8.0') && steps.openssl-cache.outputs.cache-hit == 'true' }}
        run: sudo mv /tmp/ssl /usr/local/ssl

      - name: Manually install openSSL 1.1
        if: ${{ (matrix.librabbitmq-version == '0.10.0' || matrix.librabbitmq-version == '0.9.0' || matrix.librabbitmq-version == '0.8.0') && steps.openssl-cache.outputs.cache-hit != 'true' }}
        run: |
          echo "Downloading openSSL 1.1.."
          wget -q https://www.openssl.org/source/openssl-1.1.1k.tar.gz
          echo "Extracting openSSL 1.1.."
          tar -xf openssl-1.1.1k.tar.gz > /dev/null
          cd openssl-1.1.1k
          ./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl shared zlib
          make CC='/usr/local/clang/bin/clang' CFLAGS='-fPIE'
          sudo make install

      - name: Copy openSSL 1.1 cache before save
        if: ${{ (matrix.librabbitmq-version == '0.10.0' || matrix.librabbitmq-version == '0.9.0' || matrix.librabbitmq-version == '0.8.0') && steps.openssl-cache.outputs.cache-hit != 'true' }}
        run: sudo cp -r /usr/local/ssl /tmp/ssl

      - name: Save openSSL 1.1 cache
        if: ${{ (matrix.librabbitmq-version == '0.10.0' || matrix.librabbitmq-version == '0.9.0' || matrix.librabbitmq-version == '0.8.0') && steps.openssl-cache.outputs.cache-hit != 'true' }}
        id: openssl-cache-save
        uses: actions/cache/save@v4
        with:
          path: /tmp/ssl
          key: openssl-1.1.1

      - name: Reload openSSL 1.1 config
        if: ${{ (matrix.librabbitmq-version == '0.10.0' || matrix.librabbitmq-version == '0.9.0' || matrix.librabbitmq-version == '0.8.0') }}
        run: |
          export PATH=/usr/local/ssl/bin:$PATH
          echo "OPENSSL_ROOT_DIR=/usr/local/ssl" >> $GITHUB_ENV
          echo "OPENSSL_LIBRARY_DIR=/usr/local/ssl/lib" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=/usr/local/ssl/include" >> $GITHUB_ENV
          echo "OPENSSL_LIBRARIES=/usr/local/ssl/lib" >> $GITHUB_ENV
          echo "OPENSSL_CRYPTO_LIBRARY=/usr/local/ssl/lib/libcrypto.so" >> $GITHUB_ENV
          sudo sh -c 'echo "/usr/local/ssl/lib" > /etc/ld.so.conf.d/openssl-1.1.1k.conf'
          sudo ldconfig -v

      - name: Setup PHP
        uses: shivammathur/setup-php@2.32.0
        with:
          php-version: ${{ matrix.php-version }}
          extensions: json
          coverage: none
        env:
          debug: true

      - name: Check stubs
        run: ./infra/tools/pamqp-stubs-lint

      - name: Build librabbitmq
        run: ./infra/tools/pamqp-install-librabbitmq master

      - name: Build PHP extension
        run: phpize && ./configure && make

      - name: Validate stubs
        run: ./infra/tools/pamqp-stubs-validate

      - name: Check stub coding style
        run: ./infra/tools/pamqp-stubs-format-check

      - name: Validate argument parsing
        run: ./infra/tools/pamqp-php-cli-deterministic -d extension=modules/amqp.so ./infra/tools/pamqp-arguments-validate

  test:
    name: ${{ matrix.test-php-args == '-m' && 'Memtest' || 'Test' }} php-${{ matrix.php-version }}${{ matrix.php-thread-safe && '-ts' || '-nts' }} librabbitmq-${{ matrix.librabbitmq-version }} ${{ matrix.compiler }}
    runs-on: ubuntu-22.04
    needs: prep
    if: needs.prep.outputs.should_skip != 'true'

    env:
      CC: ${{ matrix.compiler }}
      TEST_PHP_ARGS: -j4 ${{ matrix.test-php-args }}
      PHP_AMQP_HOST: localhost
      PHP_AMQP_SSL_HOST: rabbitmq.example.org
      VALGRIND_OPTS: '--suppressions=infra/tools/valgrind-suppressions'

    strategy:
      fail-fast: false
      matrix:
        php-version: ${{ fromJson(needs.prep.outputs.php_versions) }}
        php-thread-safe: [ true, false ]
        librabbitmq-version: ${{ fromJson(needs.prep.outputs.librabbitmq_versions) }}
        compiler: [gcc, clang]
        include: ${{ fromJson(needs.prep.outputs.memory_build_matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Configure hostnames
        run: sudo echo "127.0.0.1 ${{ env.PHP_AMQP_SSL_HOST }}" | sudo tee -a /etc/hosts

      - name: Generate test certificates
        run: docker compose up ca

      - name: Start RabbitMQ
        run: docker compose up -d rabbitmq

      - name: Install packages
        uses: awalsh128/cache-apt-pkgs-action@v1.4.3
        with:
          packages: cmake valgrind libc6-dbg gcc clang openssl build-essential libssl-dev checkinstall zlib1g-dev
          version: ${{ (matrix.librabbitmq-version == '0.10.0' || matrix.librabbitmq-version == '0.9.0' || matrix.librabbitmq-version == '0.8.0') && 'ubuntu-20.04' || 'ubuntu-22.04' }}

      - name: Load clang 11 cache
        id: clang-cache
        uses: actions/cache/restore@v4
        with:
          path: /tmp/clang
          key: clang-11

      - name: Copy clang 11 cache after restore
        if: ${{ steps.clang-cache.outputs.cache-hit == 'true' }}
        run: sudo mv /tmp/clang /usr/local/clang

      - name: Manually install clang 11
        if: ${{ steps.clang-cache.outputs.cache-hit != 'true' }}
        run: |
          echo "Downloading clang 11.."
          wget -q https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.1/clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10.tar.xz
          echo "Extracting clang 11.."
          tar -xvf clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10.tar.xz > /dev/null
          sudo cp -r clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10 /usr/local/clang

      - name: Copy clang 11 cache before save
        if: ${{ steps.clang-cache.outputs.cache-hit != 'true' }}
        run: sudo cp -r /usr/local/clang /tmp/clang

      - name: Save clang 11 cache
        if: ${{ steps.clang-cache.outputs.cache-hit != 'true' }}
        id: clang-cache-save
        uses: actions/cache/save@v4
        with:
          path: /tmp/clang
          key: clang-11

      - name: Load cmake 3.22 cache
        id: cmake-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            /tmp/cmake
            /usr/local/bin/cmake
          key: cmake-3.22

      - name: Copy cmake 3.22 cache after restore
        if: ${{  steps.cmake-cache.outputs.cache-hit == 'true' }}
        run: sudo mv /tmp/cmake /usr/local/share/cmake-3.22

      - name: Manually install cmake 3.22
        if: ${{  steps.cmake-cache.outputs.cache-hit != 'true' }}
        run: |
          export OPENSSL_ROOT_DIR=/usr/include/openssl
          echo "Downloading cmake 3.22.."
          wget -q https://cmake.org/files/v3.22/cmake-3.22.6.tar.gz
          echo "Extracting cmake 3.22.."
          tar -xzvf cmake-3.22.6.tar.gz > /dev/null
          cd cmake-3.22.6
          ./bootstrap CC='/usr/local/clang/bin/clang' CFLAGS='-fPIE'
          make -j$(nproc) CC='/usr/local/clang/bin/clang' CFLAGS='-fPIE'
          sudo make install

      - name: Copy cmake 3.22 cache before save
        if: ${{  steps.cmake-cache.outputs.cache-hit != 'true' }}
        run: sudo cp -r /usr/local/share/cmake-3.22 /tmp/cmake

      - name: Save cmake 3.22 cache
        if: ${{  steps.cmake-cache.outputs.cache-hit != 'true' }}
        id: cmake-cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            /tmp/cmake
            /usr/local/bin/cmake
          key: cmake-3.22

      - name: Export cmake 3.22 path
        run: export PATH=/usr/local/bin/cmake:$PATH

      - name: Load openSSL 1.1 cache
        if: ${{ (matrix.librabbitmq-version == '0.10.0' || matrix.librabbitmq-version == '0.9.0' || matrix.librabbitmq-version == '0.8.0') }}
        id: openssl-cache
        uses: actions/cache/restore@v4
        with:
          path: /tmp/ssl
          key: openssl-1.1.1

      - name: Copy openSSL 1.1 cache after restore
        if: ${{ (matrix.librabbitmq-version == '0.10.0' || matrix.librabbitmq-version == '0.9.0' || matrix.librabbitmq-version == '0.8.0') && steps.openssl-cache.outputs.cache-hit == 'true' }}
        run: sudo mv /tmp/ssl /usr/local/ssl

      - name: Manually install openSSL 1.1
        if: ${{ (matrix.librabbitmq-version == '0.10.0' || matrix.librabbitmq-version == '0.9.0' || matrix.librabbitmq-version == '0.8.0') && steps.openssl-cache.outputs.cache-hit != 'true' }}
        run: |
          echo "Downloading openSSL 1.1.."
          wget -q https://www.openssl.org/source/openssl-1.1.1k.tar.gz
          echo "Extracting openSSL 1.1.."
          tar -xf openssl-1.1.1k.tar.gz > /dev/null
          cd openssl-1.1.1k
          ./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl shared zlib
          make CC='/usr/local/clang/bin/clang' CFLAGS='-fPIE'
          sudo make install

      - name: Copy openSSL 1.1 cache before save
        if: ${{ (matrix.librabbitmq-version == '0.10.0' || matrix.librabbitmq-version == '0.9.0' || matrix.librabbitmq-version == '0.8.0') && steps.openssl-cache.outputs.cache-hit != 'true' }}
        run: sudo cp -r /usr/local/ssl /tmp/ssl

      - name: Save openSSL 1.1 cache
        if: ${{ (matrix.librabbitmq-version == '0.10.0' || matrix.librabbitmq-version == '0.9.0' || matrix.librabbitmq-version == '0.8.0') && steps.openssl-cache.outputs.cache-hit != 'true' }}
        id: openssl-cache-save
        uses: actions/cache/save@v4
        with:
          path: /tmp/ssl
          key: openssl-1.1.1

      - name: Reload openSSL 1.1 config
        if: ${{ (matrix.librabbitmq-version == '0.10.0' || matrix.librabbitmq-version == '0.9.0' || matrix.librabbitmq-version == '0.8.0') }}
        run: |
          export PATH=/usr/local/ssl/bin:$PATH
          echo "OPENSSL_ROOT_DIR=/usr/local/ssl" >> $GITHUB_ENV
          echo "OPENSSL_LIBRARY_DIR=/usr/local/ssl/lib" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=/usr/local/ssl/include" >> $GITHUB_ENV
          echo "OPENSSL_LIBRARIES=/usr/local/ssl/lib" >> $GITHUB_ENV
          echo "OPENSSL_CRYPTO_LIBRARY=/usr/local/ssl/lib/libcrypto.so" >> $GITHUB_ENV
          sudo sh -c 'echo "/usr/local/ssl/lib" > /etc/ld.so.conf.d/openssl-1.1.1k.conf'
          sudo ldconfig -v

      - name: Setup PHP
        uses: shivammathur/setup-php@2.32.0
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          extensions: simplexml
        env:
          phpts: ${{ matrix.php-thread-safe && 'ts' || 'nts' }}
          debug: true

      - name: Build librabbitmq
        run: ./infra/tools/pamqp-install-librabbitmq ${{ matrix.librabbitmq-version }}

      - name: Print librabbitmq version
        run: pkg-config librabbitmq --debug

      - name: Build PHP extension
        run: phpize && ./configure && make

      - name: Run minimal test suite
        run: make test | tee result-minimal.txt
        env:
          # Reset defaults to a) only run local tests, b) don’t run memory checks as the full test suite run will do so
          TEST_PHP_ARGS: '-j4 -q'
          PHP_AMQP_HOST: ''
          PHP_AMQP_SSL_HOST: ''

      - name: Test full test suite
        run: make test | tee result-full.txt

      - name: Benchmark PHP extension
        run: ./infra/tools/pamqp-php-cli-deterministic -d extension=modules/amqp.so benchmark.php

      - name: Dump report
        run: ./infra/tools/pamqp-test-report
